name: Deploy API to VPS

on:
  push:
    branches: [main]
    paths:
      - 'api/**'  # <- Csak API változásoknál fut

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy API via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/purzelbaum/api
            git pull origin main
            npm install --omit=dev
            pm2 reload api/ecosystem.config.cjs