name: Deploy API to VPS

on:
  push:
    branches: [main]
    paths:
      - 'api/**'  # <- Csak API változásoknál fut

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy API via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Navigate to the existing repository and pull latest changes
            cd /var/www/Purzelbaum
            git pull origin main
            
            # Navigate to API directory and install dependencies
            cd /var/www/Purzelbaum/api
            npm install --omit=dev
            
            # Reload PM2 with the correct path (we're already in api directory)
            pm2 reload ecosystem.config.cjs